version: "3"

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro

  openhab:
    image: openhab/openhab:3.0.1
    environment:
      - OPENHAB_HTTP_PORT=8080
      - OPENHAB_HTTPS_PORT=8443
      - EXTRA_JAVA_OPTS=-Duser.timezone=Europe/Rome
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ./openhab/addons:/openhab/addons
      - ./openhab/conf:/openhab/conf
      - ./openhab/userdata:/openhab/userdata
    restart: always
