---

- name: Homekit Playbook
  hosts: homekit

  vars:
    - ansible_become_pass: "{{ ansible_password }}"

  vars_prompt:
    - name: ansible_password
      prompt: homekit password?

  tasks:
#    - name: Install Docker
#      command: apt install -y docker.io docker-compose
#      become: yes

#    - name: Add homekit user
#      become: yes
#      user:
#        name: homekit
#        groups: docker
#        append: yes

    - name: Copy docker-compose.yml file
      copy:
        src: '{{ item }}'
        dest: /home/homekit/
      loop:
        - docker-compose.yml
        - index.html

    - name: Start Services
      command: docker-compose up -d
